owner: joeycreator # GitHub username
repo: upptime # GitHub repository name
user-agent: joeycreator
sites: # List of endpoints to track
  - name: Covid-19alerts
    url: https://covid-19alerts.netlify.app/main/index.html
assignees: # Users to assign downtime issues (optional)
  - Joey Cadieux
status-website: # Status website (optional)
  cname: covid-19alerts.netlify.app # Custom domain CNAME
  # baseUrl: /repo
  name: Upptime # Status website title