owner: JoeyCreator # GitHub username
repo: COVID-19ALERT # GitHub repository name
sites: # List of endpoints to track
  - name: COVID-19 ALERT
    url: https://covid-19alert.netlify.app
assignees: # Users to assign downtime issues (optional)
  - JoeyCreator
status-website: # Status website (optional)
  cname: upptime.js.org # Custom domain CNAME
  name: Upptime # Status website title